"""add_assessments_table

Revision ID: 85789fd62eff
Revises: 0536bae1be60
Create Date: 2026-05-23 17:33:41.767822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85789fd62eff'
down_revision: Union[str, None] = '0536bae1be60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('cv_result_id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(length=512), nullable=True),
    sa.Column('candidate_email', sa.String(length=255), nullable=True),
    sa.Column('assessment_name', sa.String(length=255), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('cv_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('conversation_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('fit_recommendation', sa.String(length=50), nullable=True),
    sa.Column('structured_result', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cv_result_id'], ['cv_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['screening_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_cv_result_id'), 'assessments', ['cv_result_id'], unique=False)
    op.create_index(op.f('ix_assessments_job_id'), 'assessments', ['job_id'], unique=False)
    op.create_index(op.f('ix_assessments_uid'), 'assessments', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_uid'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_job_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_cv_result_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
