"""add_candidate_email

Revision ID: 8e50fd9a084b
Revises: 8114118c8e5b
Create Date: 2026-05-22 19:08:30.959181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e50fd9a084b'
down_revision: Union[str, None] = '8114118c8e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_results', sa.Column('candidate_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_results', 'candidate_email')
    # ### end Alembic commands ###
