"""add_candidate_email

Revision ID: 8114118c8e5b
Revises: 96e8175c3499
Create Date: 2026-05-22 19:04:22.326259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8114118c8e5b'
down_revision: Union[str, None] = '96e8175c3499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
